### PR TITLE
fix(a11y): add role and tabindex to crop resize handles

### LINKED ISSUE #1222: A11y warning in crop resize handles in PhotoEditDialog
### What
Build emits an accessibility warning in the image editor because an interactive crop resize handle has a pointer event handler but no explicit ARIA role.

Affected location: PhotoEditDialog.svelte

### Steps to reproduce the behavior:
1. Clone the repository and install dependencies with pnpm install --frozen-lockfile
2. Copy environment variables file: copy .env (Windows)
3. Run pnpm build
4. Check Terminal Output
5. See warning: transforming (434) node_modules\.pnpm\devalue@5.6.4\node_modules\devalue\src\parse.js7:05:10 pm [vite-plugin-svelte] src/lib/ui/images/PhotoEditDialog.svelte:560:7 `<cropper-handle>` with a pointerdown handler must have an ARIA role
https://svelte.dev/e/a11y_no_static_element_interactions

### Expected behavior
Build should complete without this accessibility warning. Interactive elements with pointer handlers should include proper accessibility semantics.

### Screenshots

Image

### Platform (Desktop, Mobile, Hunger Games)
 - OS: Windows
 - Platform Desktop

### Part of
N/A (new issue)

### PR DESCRIPTION
**Pull request by Namraa310806**
### Description

This PR fixes an accessibility warning in the image editor crop resize handles.

The build was reporting an a11y warning because an interactive custom element had a pointer interaction without explicit accessibility semantics.  
This fix adds proper semantics to the resize handle element in `PhotoEditDialog.svelte`, making it identifiable and focusable for assistive technologies.

### Summary of changes
- Added `role="button"` to the interactive resize handle  
- Added `tabindex="0"` to make it keyboard-focusable  
- Added keyboard support (`Enter` and `Space`) for accessibility compliance  
- Preserved existing `aria-label` for screen reader support   

### Screenshot or video
No visual UI changes.

The following screenshot shows the build output after the fix, where the accessibility warning is no longer present:

Screenshot 2026-03-20 192510

### Related issue(s)
- Fixes #1222

---

### Checklist: Author Self-Review

- [x] I have performed a self-review of my own code (including running it)  
- [x] I understand the changes I'm proposing and why they are needed  
- [x] My changes generate no new warnings or errors (linting, console)  
- [ ] I have made corresponding changes to the documentation (if applicable)  

---

## Large Language Models usage disclosure

- [x] Used AI assistance for drafting issue description and refining PR text

## Summary by CodeRabbit

* **Bug Fixes**
  * Photo crop resize handles are keyboard-focusable, respond to Enter/Space, and have per-handle accessible labels so screen readers announce each handle's action.

* **UI Updates**
  * Search "Sort by" label now uses localized text and its dropdown exposes expanded/collapsed state to assistive tech.
  * Mobile header spacing adjusted for improved layout.

* **Chores**
  * Added localization text for resize-handle accessibility.

### CODE REVIEW

**Comment by VaiTon** [comment]
@coderabbitai review

File: src/lib/ui/images/PhotoEditDialog.svelte [hunk 1]
```diff
@@ -561,7 +561,15 @@
...
-								aria-label="Resize crop selection"
+								onkeydown={(e: KeyboardEvent) => {
+									if (e.key === 'Enter' || e.key === ' ') {
+										e.preventDefault();
+										enableCropping();
+									}
+								}}
+								role="button"
+								tabindex="0"
+								aria-label={`Resize ${action} handle`}
```
Comment (VaiTon) [inline src/lib/ui/images/PhotoEditDialog.svelte]: This should be translatable.

File: git
Comment (VaiTon) [inline git:1]: Not part of this PR.

**Review by VaiTon — CHANGES_REQUESTED** [review]

File: src/lib/ui/images/PhotoEditDialog.svelte (hunk 1 above)
Comment (Namraa310806) [reply src/lib/ui/images/PhotoEditDialog.svelte]: Thanks for pointing this out!

I've updated the aria-label to use the project's i18n system. The string has been moved to the translation file (`en-US.json`) and is now referenced via the translation function with the dynamic `{action}` value.

Let me know if you'd like this key placed elsewhere or named differently.

File: git
Comment (Namraa310806) [reply git:1]: You're right — there were some unrelated changes included earlier due to syncing with upstream.

I've cleaned up the branch and ensured that only the relevant accessibility and i18n changes are part of this PR now.

**Review by VaiTon — APPROVED** [review]
