### PR TITLE
fix: text inside tags getting clipped on mobile browsers

### LINKED ISSUE #489: Text inside tags are getting clipped on mobile browsers
### What
Some of the text inside the tags(Categories) are getting clipped only in mobile browsers.

### Screenshots

Image

### PR DESCRIPTION
**Pull request by swastikCommits**
## Description
Added `flex` and `items-center` to ensure proper alignment of content within badges and `break-words` to allow long text to wrap naturally instead of being cut off.

## Screenshots
WhatsApp Image 2025-04-19 at 16 35 12_48e5219c

Fixes #489 

---

## Checklist:

**Author Self-Review:**

- [x] I have performed a self-review of my own code.
- [x] I understand the changes I'm proposing and why they are needed.
- [x] My changes generate no new warnings or errors (linting, console).
- [x] I have made corresponding changes to the documentation (if applicable).

### CODE REVIEW

File: src/routes/products/[barcode]/+page.svelte [hunk 1]
```diff
@@ -108,12 +108,12 @@
...
 
 				<span class="text-end font-bold">Brands:</span>
-				<div>
+				<div class="flex flex-wrap gap-1">
 					{#await data.taxo.brands}
 						Loading...
 					{:then brands}
 						{#each product.brands_tags as tag, i (i)}
-							<span class="badge">
+							<span class="badge flex h-auto items-center break-words">
```
Comment (VaiTon) [inline src/routes/products/[barcode]/+page.svelte:116]: Do we need `flex items-center` ?

File: src/routes/products/[barcode]/+page.svelte [hunk 2]
```diff
@@ -126,66 +126,69 @@
 						Loading...
 					{:then categories}
 						{#each product.categories_tags as tag (tag)}
-							<a class="badge badge-secondary" href="/taxo/categories/{tag}">
+							<a
+								class="badge badge-secondary flex h-auto items-center break-words"
```
Comment (VaiTon) [inline src/routes/products/[barcode]/+page.svelte:130]: Same here

File: src/routes/products/[barcode]/+page.svelte [hunk 3]
```diff
@@ -126,66 +126,69 @@
...
 
 				<span class="text-end font-bold">Stores:</span>
-				<div>
+				<div class="flex flex-wrap gap-1">
 					{#await data.taxo.stores}
 						Loading...
 					{:then stores}
 						{#each product.stores_tags as tag, i (i)}
-							<span class="badge">
+							<span class="badge flex h-auto items-center break-words">
```
Comment (VaiTon) [inline src/routes/products/[barcode]/+page.svelte:145]: Same here

File: src/routes/products/[barcode]/+page.svelte [hunk 4]
```diff
@@ -126,66 +126,69 @@
...
 
 				<span class="text-end font-bold">Labels:</span>
-				<span>
+				<div class="flex flex-wrap gap-1">
 					{#await data.taxo.labels}
 						Loading...
 					{:then labels}
 						{#each product.labels_tags as tag, i (i)}
-							<a class="badge" href={'/taxo/labels/' + tag}>
+							<a class="badge flex h-auto items-center break-words" href={'/taxo/labels/' + tag}>
```
Comment (VaiTon) [inline src/routes/products/[barcode]/+page.svelte:158]: Same here

File: src/routes/products/[barcode]/+page.svelte [hunk 5]
```diff
@@ -126,66 +126,69 @@
...
 
 				<span class="text-end font-bold">Countries:</span>
-				<span>
+				<div class="flex flex-wrap gap-1">
 					{#await data.taxo.countries}
 						Loading...
 					{:then countries}
 						{#each product.countries_tags as tag, i (i)}
-							<a class="badge" href={'/taxo/countries/' + tag}>
+							<a class="badge flex h-auto items-center break-words" href={'/taxo/countries/' + tag}>
```
Comment (VaiTon) [inline src/routes/products/[barcode]/+page.svelte:171]: Same here

File: src/routes/products/[barcode]/+page.svelte [hunk 6]
```diff
@@ -126,66 +126,69 @@
...
-				<span>
+				<div class="flex flex-wrap gap-1">
 					{#await data.taxo.origins}
 						Loading...
 					{:then origins}
 						{#each product.origins_tags as tag, i (i)}
 							{#if i > 0},
 							{/if}
-							<a class="link" href={'/taxo/origin/' + tag}>
+							<a class="link inline-flex items-center break-words" href={'/taxo/origin/' + tag}>
```
Comment (VaiTon) [inline src/routes/products/[barcode]/+page.svelte:186]: Was this also not rendering correctly? Could you provide an example?

Comment (swastikCommits) [reply src/routes/products/[barcode]/+page.svelte:186]: Here, it was fine, though due to the small text. 
To be on the safer side, I fixed these tags too coz if we had a long text inside the tag it will propoerly get clipped too.

File: src/routes/products/[barcode]/+page.svelte (hunk 1 above)
Comment (swastikCommits) [reply src/routes/products/[barcode]/+page.svelte:116]: The badge class provides some styling already, so removing `flex` and `items-center` did not make any change. So I'm removing them.

File: src/routes/products/[barcode]/+page.svelte (hunk 2 above)
Comment (swastikCommits) [reply src/routes/products/[barcode]/+page.svelte:130]: Yeah, removing them as they did not add much value here.

File: src/routes/products/[barcode]/+page.svelte (hunk 3 above)
Comment (swastikCommits) [reply src/routes/products/[barcode]/+page.svelte:145]: Yeah, removing them as they did not add much value here.

File: src/routes/products/[barcode]/+page.svelte (hunk 4 above)
Comment (swastikCommits) [reply src/routes/products/[barcode]/+page.svelte:158]: Yeah, removing them as they did not add much value here.

File: src/routes/products/[barcode]/+page.svelte (hunk 5 above)
Comment (swastikCommits) [reply src/routes/products/[barcode]/+page.svelte:171]: Yeah, removing them as they did not add much value here.
