### PR TITLE
fix: Don't show rotating icon for missing image in product page (fixes #413)

### LINKED ISSUE #413: Don't show rotating icon for placeholder.svg
If there is no image available the rotate button should not be shown. 
(Note: in the screenshot the default image is not seen due to #373)

Image

### PR DESCRIPTION
**Pull request by akashshetty1997**
### What
- If there is no image available the rotate button should not be shown.

### Screenshot
Before -  
image

After - 
image

### Fixes bug(s)
- Hide rotate button when no image is available

### Part of 
- [413](https://github.com/openfoodfacts/openfoodfacts-explorer/issues/413)

### Testing
- [x] Verified rotate button appears when image exists
- [x] Verified rotate button is hidden when no image source
- [x] Confirmed rotation functionality still works when button visible

### CODE REVIEW

**Comment by VaiTon** [comment]
> If there is no image available the rotate button should not be shown.

If there is no image available **the entire image block should not be shown**.

**Comment by akashshetty1997** [comment]
alright i will add that too.

**Comment by github-throwaway** [comment]
> > If there is no image available the rotate button should not be shown.
> 
> 
> 
> If there is no image available **the entire image block should not be shown**.

I think @teolemon wanted the default placeholder to be shown though.

**Comment by VaiTon** [comment]
> I think @teolemon wanted the default placeholder to be shown though.

Right, so the logic should be:
- no image: placeholder 
- image: ImageComponent with rotation, ecc...

cc @akashshetty1997

**Comment by akashshetty1997** [comment]
image

- Modified ImageButton.svelte to show a placeholder SVG when no source image exists
- Maintained rotation button behavior to only appear when an actual image is present
- Improved layout to ensure consistent sizing and positioning of both actual images and placeholders

**Comment by github-throwaway** [comment]
- The placeholder should not be dark to increase readability.
- I would also expect there be a bounding box around the placeholder. Similar to photos.

**Comment by akashshetty1997** [comment]
@github-throwaway Should the placeholder have a border even though photos don't?

1) Desktop light mode
image

2) Mobile light mode
image

3) Desktop Dark mode
image

4) Mobile Dark mode
image
 

- [x] The placeholder should not be dark in dark mode to increase readability.
- [x] I would also expect there be a bounding box around the placeholder. Similar to photos.
- [x] please provide screenshots for dark/light theme and desktop and mobile

**Comment by github-throwaway** [comment]
Don't add a border. Instead update the background Color of the placeholder. 

Light mode looks good imho. 

Dark mode still needs some work. 
Let's try making the foreground Color of the placeholder the same color as the primary button Color. And the background Color the same as in light mode. 


image
image

**Comment by akashshetty1997** [comment]
Light mode 
image

Dark mode
image

Hey @github-throwaway! For the SVG color feature we needed, I went with inline SVGs using the currentColor approach with CSS classes to control the colors. This seemed like the best practice since it works nicely with dark/light themes and keeps everything consistent with our design system.
I noticed you might have wanted an img src approach instead? I'm happy to switch to that if you prefer, but wanted to check with you first since the current method gives us more styling flexibility. Let me know what you think!

**Comment by github-throwaway** [comment]
You are missing the background Color in dark mode.

**Comment by akashshetty1997** [comment]
image

**Comment by github-throwaway** [comment]
I don’t know. I think in light mode we are good. I’m not satisfied with the dark placeholder though. Could you try to make the background the same color as in the light mode? Or do you have an idea yourself?

**Comment by akashshetty1997** [comment]
Sure, I can make it match the light mode color. Though with our brown dark background, a super light placeholder might be a bit jarring for users.

I'll play around with some different colors and see what actually looks good with our dark theme. Give me a bit to experiment and I'll show you a few options that might work better!

**Comment by abrahamvg** [comment]
Hi @akashshetty1997 
Had made some iterations, just to help out.
1. Colour Scheme :
   Bg: #26201D, Icon: #EBC3A8
   image
 2. Generic placeholder for both colour theme, to keep it consistent (My recomendation) :
   Bg: #ECECEC, Icon: #777777
   image

**Comment by github-throwaway** [comment]
Thanks @abrahamvg. I like the second option too! Let's go with that one :)

**Comment by akashshetty1997** [comment]
@abrahamvg  thank you so much for helping. so @github-throwaway  as we going with second option should i chnage it for light view also?

**Comment by akashshetty1997** [comment]
Web dark mode -
image

Mobile dark mode - 
image


Web light mode -
image

Mobile light mode -
image

**Comment by github-throwaway** [comment]
LGTM. Thanks! 🙏

**Comment by akashshetty1997** [comment]
Hey @VaiTon, @github-throwaway — if everything looks good, feel free to go ahead with the merge request!

File: src/lib/ui/ImageButton.svelte [hunk 1]
```diff
@@ -18,22 +18,35 @@
...
-		class="btn btn-circle btn-sm bg-base-100/80 hover:bg-base-100 absolute right-2 bottom-2"
-		onclick={(e) => {
-			e.stopPropagation();
-			rotateImage();
-		}}
-		title="Rotate image"
-		aria-label="Rotate image 90 degrees clockwise"
-	>
-		<span class="icon-[mdi--rotate-right] h-4 w-4"></span>
+		{#if src}
```
Comment (VaiTon) [inline src/lib/ui/ImageButton.svelte:21]:
```suggestion
		{#if src != null}
```

File: src/lib/ui/ImageButton.svelte [hunk 2]
```diff
@@ -18,22 +18,35 @@
...
+		{:else}
+			<div
+				class="flex min-h-[120px] min-w-[120px] items-center justify-center rounded-lg bg-gray-200"
+			>
+				<img src="/Placeholder.svg" alt="Image not available" height="24" aria-hidden="true" />
+			</div>
+		{/if}
 	</button>
+
+	{#if src}
```
Comment (VaiTon) [inline src/lib/ui/ImageButton.svelte:39]: Same here

**Review by VaiTon — CHANGES_REQUESTED** [review]

**Review by VaiTon — APPROVED** [review]
Thank you!
