### PR TITLE
Fix: Resolve Horizontal Overflow Issue (Edit Page)

### LINKED ISSUE #190: UI Overflow Issue in Categories Section on Edit Page
### 📌 Issue Description  
The **categories section** on the edit page has an **overflow issue**, causing long category names to exceed the container width instead of wrapping properly. This affects usability, making it harder to view or remove categories.

### 🔍 Steps to Reproduce  
1. Go to the **edit page** of a product.  
2. Add multiple categories with long names.  
3. Observe how some category names overflow beyond the container.  

### ✅ Expected Behavior  
- Category names should **wrap properly** within the container.  
- The UI should **remain readable and responsive** without breaking layout.  

### 💡 Possible Fix  
- Implement **text wrapping** or add an **ellipsis (`...`)** for long category names.  
- Ensure the container supports **sufficient space** for long text.  

### 📸 Screenshot  
1. 
Image

2. 
Image

---

🛠 **Would appreciate any feedback on this issue!**

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
### 📌 **Description**  
This PR fixes the **horizontal overflow issue** in the tag input field by ensuring tags do not extend beyond the container and allowing proper behavior.  

### 🔧 **Changes Made**  
✅ Added `overflow-y-auto` to enable horizontal scrolling  
✅ Ensured the input field remains within the container  
✅ Improved spacing and layout for better UX  

### 🎯 **Fixes**  
- Closes #190 

#### Before (Overflow Issue)  
image

#### After (Fixed Overflow)  
Screenshot from 2025-03-03 00-51-54

### **Video**
[Screencast from 03-03-25 12:52:00 AM IST.webm](https://github.com/user-attachments/assets/ead4996b-0b13-4bd3-aa1b-d40ba1278633)

### 🛠 **How to Test**  
1. Add multiple tags to the input field.  
2. Ensure they **stay within the container** and scroll horizontally when needed.  
3. Confirm that the input field remains **functional and responsive**.  

> This fix improves usability without introducing breaking changes.

### CODE REVIEW

File: src/routes/products/[barcode]/edit/Tags.svelte [hunk 1]
```diff
@@ -57,15 +56,15 @@
 	<div class="dropdown grow">
 		<input
 			type="text"
-			class="w-full bg-transparent outline-hidden"
+			class="h-auto w-auto min-w-0 flex-shrink border-none bg-transparent outline-none"
```
Comment (VaiTon) [inline src/routes/products/[barcode]/edit/Tags.svelte:59]: Do we need `min-w-0` and `flex-shrink`?

File: src/routes/products/[barcode]/edit/Tags.svelte [hunk 2]
```diff
@@ -57,15 +56,15 @@
...
 			onkeydown={inputHandler}
 			bind:value={newValue}
 		/>
 
 		{#if filteredAutocomplete.length > 0}
 			<div class="dropdown-content max-h-52 overflow-y-auto">
 				<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
-				<ul tabindex="0" class="menu bg-base-100 shadow-xs">
+				<ul tabindex="0" class="menu bg-base-100 border-none shadow-none">
```
Comment (VaiTon) [inline src/routes/products/[barcode]/edit/Tags.svelte:67]: Is there any reason for this style change?

**Comment by VaiTon** [comment]
Also

> ✅ Added overflow-x-auto to enable horizontal scrolling

Where? I can't seem to find it in the diff

**Comment by SyedImtiyaz-1** [comment]
> Also
> 
> > ✅ Added overflow-x-auto to enable horizontal scrolling
> 
> Where? I can't seem to find it in the diff

Apologies, I meant overflow-y-auto, not overflow-x-auto. My bad for the typo!

**Comment by SyedImtiyaz-1** [comment]
I’ve removed min-w-0, flex-shrink, border-none, and shadow-none and pushed the changes back. The reason for this change is to ensure better layout consistency and avoid unnecessary overrides. Thanks for noticing! Let me know if any further adjustments are needed.

**Comment by VaiTon** [comment]
> > Also
> > > ✅ Added overflow-x-auto to enable horizontal scrolling
> > 
> > 
> > Where? I can't seem to find it in the diff
> 
> Apologies, I meant overflow-y-auto, not overflow-x-auto. My bad for the typo!

From the issue

> The categories section on the edit page has an overflow issue, causing long category names to exceed the container width instead of wrapping properly. This affects usability, making it harder to view or remove categories.

With this PR we're fixing y axis overflow. It doesn't close the issue as if we're on a smarphone, with a big enough category it may overflow, right?

**Comment by SyedImtiyaz-1** [comment]
> > > Also
> > > > ✅ Added overflow-x-auto to enable horizontal scrolling
> > > 
> > > 
> > > Where? I can't seem to find it in the diff
> > 
> > 
> > Apologies, I meant overflow-y-auto, not overflow-x-auto. My bad for the typo!
> 
> From the issue
> 
> > The categories section on the edit page has an overflow issue, causing long category names to exceed the container width instead of wrapping properly. This affects usability, making it harder to view or remove categories.
> 
> With this PR we're fixing y axis overflow. It doesn't close the issue as if we're on a smarphone, with a big enough category it may overflow, right?

Thank you for pointing. I've just pushed the code again with the optimizations. (responsive for all devices)

**Comment by SyedImtiyaz-1** [comment]
### Video of the fixes : 

[Screencast from 03-03-25 06:20:15 AM IST.webm](https://github.com/user-attachments/assets/f5221402-6cc7-4247-b461-14f4b3ecbd4c)

**Comment by VaiTon** [comment]
Please run `pnpm format`

**Comment by SyedImtiyaz-1** [comment]
> Please run `pnpm format`

@VaiTon can you please review this now ?

**Comment by VaiTon** [comment]
Thank you :tada:
