### PR TITLE
fix: fixed content overflow on Folksonomy

### LINKED ISSUE #501: Content overflowing in Folksonomy engine
### What
Content overflowing in folksonomy engine

Image

Image

### PR DESCRIPTION
**Pull request by Bhavishya2601**
## Description

Fixed the content overflow on Folksonomy 

Before
image

After
image

Fixes #501 

---

## Checklist:

**Author Self-Review:**

- [x] I have performed a self-review of my own code.
- [x] I understand the changes I'm proposing and why they are needed.
- [x] My changes generate no new warnings or errors (linting, console).
- [x] I have made corresponding changes to the documentation (if applicable).

### CODE REVIEW

File: src/routes/folksonomy/+page.svelte [hunk 1]
```diff
@@ -198,15 +198,15 @@
...
 			role="button"
 			tabindex="0"
 			aria-expanded={expandedGroups[group] ? 'true' : 'false'}
 			onclick={() => toggleGroup(group)}
 			onkeydown={(e) => handleGroupKeyDown(e, group)}
 		>
-			<div class="flex items-center gap-2">
-				<span>{group}</span>
+			<div class="flex items-center gap-2 overflow-hidden">
+				<span class="truncate">{group}</span>
```
Comment (VaiTon) [inline src/routes/folksonomy/+page.svelte:209]: I'm not sure about this one. I'd like to see the entire tags even on smaller devices. Can we try instead to `break-all`?

**Review by VaiTon — CHANGES_REQUESTED** [review]
