### PR TITLE
fix: fixed header issues on smaller screens

### LINKED ISSUE #496: Header responsiveness issues on Smaller screens
### What

-  The header is not responsive on smaller screens
- Extra padding on smaller screens in 'Welcome to OFF section'

Image

### PR DESCRIPTION
**Pull request by Bhavishya2601**
## Description

- The header was not responsive on smaller screens
- 'Welcome to OFF' has double padding

Before
image

After

https://github.com/user-attachments/assets/d4ac6369-1362-4573-92e2-57eaf94a379a

Fixes #496 

---

## Checklist:

**Author Self-Review:**

- [x] I have performed a self-review of my own code.
- [x] I understand the changes I'm proposing and why they are needed.
- [x] My changes generate no new warnings or errors (linting, console).
- [x] I have made corresponding changes to the documentation (if applicable).

**LLM Usage Disclosure:** not used

### CODE REVIEW

File: src/routes/+layout.svelte [hunk 1]
```diff
@@ -108,13 +108,13 @@
 </div>
 
 <div class="bg-base-100 top-0 right-0 left-0 z-50 mx-4 xl:hidden">
-	<div class="navbar bg-base-100 mx-auto mt-2 mb-2 max-w-7xl">
```
Comment (VaiTon) [inline src/routes/+layout.svelte:111]: This class right here makes the navbar have a max width when the screen is big enough. We need it

File: src/routes/+layout.svelte [hunk 2]
```diff
@@ -108,13 +108,13 @@
...
+	<div class="navbar bg-base-100 mx-auto mt-2 mb-2 px-0">
```
Comment (VaiTon) [inline src/routes/+layout.svelte:111]: Why?

File: src/routes/+layout.svelte [hunk 3]
```diff
@@ -108,13 +108,13 @@
...
 		<div class="navbar-start">
 			<a href="/">
 				<Logo />
 			</a>
 		</div>
-		<div class="navbar-end flex gap-2">
+		<div class="navbar-end flex gap-1 sm:gap-2">
```
Comment (VaiTon) [inline src/routes/+layout.svelte:117]: Why?

**Review by VaiTon — CHANGES_REQUESTED** [review]

File: src/routes/+layout.svelte (hunk 2 above)
Comment (Bhavishya2601) [reply src/routes/+layout.svelte:111]: navbar class is giving a padding of 0.5rem (8px), so px-0 is used for overriding it

File: src/routes/+layout.svelte (hunk 3 above)
Comment (Bhavishya2601) [reply src/routes/+layout.svelte:117]: To get a little more space between logo and btn's

with `gap-2`
image

with `gap-1 sm:gap-2`
image

Just a minor difference but I think so it looks good with gap-1, you can give me, your pov on this

File: src/routes/+layout.svelte (hunk 1 above)
Comment (Bhavishya2601) [reply src/routes/+layout.svelte:111]: @VaiTon I just checked, isn't this navbar for smaller devices which gets hidden after `xl` by property `xl:hidden`, I think the  `max-w-7xl` is placed in wrong place, it should be in the navbar which is for larger devices

correct me if I'm wrong

Comment (VaiTon) [reply src/routes/+layout.svelte:111]: That's right, thanks!

**Review by VaiTon — APPROVED** [review]
